# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bidirectional.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x62idirectional.proto\x12\x0fshoppingService\"!\n\rClientMessage\x12\x10\n\x08itemName\x18\x01 \x01(\t\"4\n\rServerMessage\x12\x10\n\x08itemName\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\t2b\n\rBidirectional\x12Q\n\tChatOrder\x12\x1e.shoppingService.ClientMessage\x1a\x1e.shoppingService.ServerMessage\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bidirectional_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CLIENTMESSAGE']._serialized_start=40
  _globals['_CLIENTMESSAGE']._serialized_end=73
  _globals['_SERVERMESSAGE']._serialized_start=75
  _globals['_SERVERMESSAGE']._serialized_end=127
  _globals['_BIDIRECTIONAL']._serialized_start=129
  _globals['_BIDIRECTIONAL']._serialized_end=227
# @@protoc_insertion_point(module_scope)
